source 'https://github.com/CocoaPods/Specs.git'
platform :osx, "10.10"
use_frameworks!

target 'Example_for_WDFlickrPhotoUploader', :exclusive => true do
  pod "WDFlickrPhotoUploader", :path => "../"
end

target 'WDFlickrPhotoUploader_Tests', :exclusive => true do
  pod "WDFlickrPhotoUploader", :path => "../"

  pod 'OCMock', :inhibit_warnings => true
  pod 'Specta'
  pod 'Expecta'
end
